export const dpValidations = {
    CDSLDetails: {
        "BOCategory": "Please select BO Category in CDSL details",
        "CurrencyCode": "Please select Currency Code in CDSL details",
        "Occupation": "Please select Occupation in CDSL details",
        "StatementCyclecode": "Please enter Settlement Cycle Code in CDSL details"
    },
    DPDetails: {
        "Addressforcommunication": "Please select Address For Communication/ Corporate Benefits",
        "Autopledgeconfirmation": "Please opt if Standing instruction For Auto Pledge Confirmation is required",
        "Branch": "Please enter Branch",
        "dp": "Please select a DP",
        "DPHolderShortName": "Please enter DP Holder Short Name",
        "dpid": "Please select a DP ID",
        "dpname": "Please enter DP Name",
        "DPThirdpartyHouserName": "Please enter DP Third Party Address 1",
        "DPThirdpartyHouserNumber": "Please enter DP Third Party Address 2",
        "DPThirdpartyName": "Please enter DP Third Party Name",
        "DPThirdpartystreet": "Please enter DP Third Party Address 3",
        "EmailIDforCommunication": "Please enter Email ID For Communication",
        "EmailSharingwithRTA": "Please opt if Email Sharing with RTA is required",
        "NoofHolders": "Please enter No. Of Holders",
        "receivecreditsautomatically": "Please opt if you Wish To Receive Credits Automatically Into Credits Account",
        "RiskCountry": "Please enter Risk Country",
        "RSDAFlag": "Please enter RSDA Flag",
        "Sendallcommunicationsstatementsthroughemailonly": "Please opt if All Communications/Statements is to be Received Through Email",
        "SubTypeofCDSLDP": "Please select Sub Type Of CDSL DP",
        "SubTypeofNSDLDP": "Please select Sub Type Of NSDL DP",
        "TypeofCDSLDP": "Please select Type Of CDSL DP",
        "TypeofNSDLDP": "Please select Type Of NSDL DP",
        "VoucherId": "Please enter Voucher ID",
        KitNO:"Please enter Kit number "
    },


    MinorGuardian: {
        "minorguardianCity": "Please enter City in DP Guardian Details",
        "minorguardianCountry": "Please enter Country in DP Guardian Details",
        "minorguardianFirstName": "Please enter First Name in DP Guardian Details",
        "minorguardianHouseName": "Please enter Address 1 in DP Guardian Details",
        "minorguardianHouseNumber": "Please enter Address 2 in DP Guardian Details",
        "minorguardianIdentificaitonDetails": "Please enter Identification Proof in DP Guardian Details",
        "minorguardianPin": "Please enter PinCode in DP Guardian Details",
        "minorguardianProofNumber": "Please enter Identification Proof Details in DP Guardian Details",
        "minorguardianRelationshipofGuardian": "Please select Relationship With Applicant in DP Guardian Details",
        "minorguardianState": "Please enter State in DP Guardian Details",
        "minorguardianStreet": "Please enter Address 3 in DP Guardian Details",
        "minorguardianTitle": "Please select Title for DP Guardian Details"
    },


    FirstNomineeDetails: {
        "guardianCity": "Please enter First Minor Nominee Guardian City in DP Minor Nominee Guardian Details",
        "guardianCountry": "Please enter First Minor Nominee Guardian  Country in DP Minor Nominee Guardian Details",
        "guardianFirstName": "Please enter First Minor Nominee Guardian  First Name in DP Minor Nominee Guardian Details",
        "guardianHouseName": "Please enter First Minor Nominee Guardian  Address 1 in DP Minor Nominee Guardian Details",
        "guardianHouseNumber": "Please enter First Minor Nominee Guardian  Address 2 in DP Minor Nominee Guardian Details",
        "guardianIdentificaitonDetails": "Please enter First Minor Nominee Guardian  Identification Proof in DP Minor Nominee Guardian Details",
        "guardianIdNumber": "Please enter First Minor Nominee Guardian  Identification Proof Details in DP Minor Nominee Guardian Details",
        "guardianPin": "Please enter First Minor Nominee Guardian  PinCode in DP Minor Nominee Guardian Details",
        "guardianRelationshipofGuardian": "Please select  First Minor Nominee Guardian Relationship With Applicant in DP Minor Nominee Guardian Details",
        "guardianState": "Please enter  First Minor Nominee Guardian State in DP Minor Nominee Guardian Details",
        "guardianStreet": "Please enter First Minor Nominee Guardian  Address 3 in DP Minor Nominee Guardian Details",
        "guardianTitle": "Please select  First Minor Nominee Guardian Title for DP Minor Nominee Guardian Details",
        "nomineeCity": "Please enter First Nominee City in DP Nominee Details",
        "nomineeCountry": "Please enter First Nominee Country in DP Nominee Details",
        "nomineeDOB": "Please enter First Nominee DOB in DP Nominee Details",
        "nomineeEqualShareForNominess": "Please select option for First Nominee Equal Share For Nominees in DP Nominee Details",
        "nomineeFirstName": "Please enter First Nominee First Name in DP Nominee Details ",
        "nomineeHouseName": "Please enter First Nominee Address 1 in DP Nominee Details",
        "nomineeHouseNumber": "Please enter First Nominee Address 2 in DP Nominee Details",
        "nomineeIdNumber": "Please enter First Nominee Identification Proof Details in DP Nominee Details",
        "nomineeNomineeIdentificaitonDetails": "Please enter First Nominee Identification Proof in DP Nominee Details",
        "nomineePin": "Please enter First Nominee PinCode in DP Nominee Details",
        "nomineeRelationshipwithapplicant": "Please select First Nominee Relationship With Applicant in DP Nominee Details",
        "nomineeState": "Please enter First Nominee State in DP Nominee Details",
        "nomineeStreet": "Please enter First Nominee Address 3 in DP Nominee Details",
        "nomineeTitle": "Please select First Nominee Title for DP Nominee",
        "sharePercentage": "Please enter First Nominee the % of Share in DP Nominee Details"
    },

    SecondNomineeDetails: {
        "guardianCity": "Please enter Second Minor Nominee Guardian City in DP Minor Nominee Guardian Details",
        "guardianCountry": "Please enter Second Minor Nominee Guardian  Country in DP Minor Nominee Guardian Details",
        "guardianFirstName": "Please enter Second Minor Nominee Guardian  First Name in DP Minor Nominee Guardian Details",
        "guardianHouseName": "Please enter Second Minor Nominee Guardian  Address 1 in DP Minor Nominee Guardian Details",
        "guardianHouseNumber": "Please enter Second Minor Nominee Guardian  Address 2 in DP Minor Nominee Guardian Details",
        "guardianIdentificaitonDetails": "Please enter Second Minor Nominee Guardian  Identification Proof in DP Minor Nominee Guardian Details",
        "guardianIdNumber": "Please enter Second Minor Nominee Guardian  Identification Proof Details in DP Minor Nominee Guardian Details",
        "guardianPin": "Please enter  Second Minor Nominee Guardian PinCode in DP Minor Nominee Guardian Details",
        "guardianRelationshipofGuardian": "Please select Second Minor Nominee Guardian  Relationship With Applicant in DP Minor Nominee Guardian Details",
        "guardianState": "Please enter Second Minor Nominee Guardian  State in DP Minor Nominee Guardian Details",
        "guardianStreet": "Please enter Second Minor Nominee Guardian  Address 3 in DP Minor Nominee Guardian Details",
        "guardianTitle": "Please select Second Minor Nominee Guardian  Title for DP Minor Nominee Guardian Details",
        "nomineeCity": "Please enter Second Nominee City in DP Nominee Details",
        "nomineeCountry": "Please enter Second Nominee  Country in DP Nominee Details",
        "nomineeDOB": "Please enter Second Nominee  Nominee DOB in DP Nominee Details",
        "nomineeEqualShareForNominess": "Please select option for Second Nominee  Equal Share For Nominees in DP Nominee Details",
        "nomineeFirstName": "Please enter Second Nominee  First Name in DP Nominee Details ",
        "nomineeHouseName": "Please enter Second Nominee  Address 1 in DP Nominee Details",
        "nomineeHouseNumber": "Please enter Second Nominee  Address 2 in DP Nominee Details",
        "nomineeIdNumber": "Please enter Second Nominee  Identification Proof Details in DP Nominee Details",
        "nomineeNomineeIdentificaitonDetails": "Please enter Second Nominee  Identification Proof in DP Nominee Details",
        "nomineePin": "Please enter Second Nominee  PinCode in DP Nominee Details",
        "nomineeRelationshipwithapplicant": "Please select Second Nominee  Relationship With Applicant in DP Nominee Details",
        "nomineeState": "Please enter Second Nominee  State in DP Nominee Details",
        "nomineeStreet": "Please enter Second Nominee  Address 3 in DP Nominee Details",
        "nomineeTitle": "Please select Second Nominee  Title for DP Nominee",
        "sharePercentage": "Please enter Second Nominee  the % of Share in DP Nominee Details"
    },
    ThirdNomineeDetails: {
        "guardianCity": "Please enter Third Minor Nominee Guardian City in DP Minor Nominee Guardian Details",
        "guardianCountry": "Please enter Third Minor Nominee Guardian Country in DP Minor Nominee Guardian Details",
        "guardianFirstName": "Please enter Third Minor Nominee Guardian  First Name in DP Minor Nominee Guardian Details",
        "guardianHouseName": "Please enter Third Minor Nominee Guardian  Address 1 in DP Minor Nominee Guardian Details",
        "guardianHouseNumber": "Please enter Third Minor Nominee Guardian  Address 2 in DP Minor Nominee Guardian Details",
        "guardianIdentificaitonDetails": "Please enter Third Minor Nominee Guardian  Identification Proof in DP Minor Nominee Guardian Details",
        "guardianIdNumber": "Please enter Third Minor Nominee Guardian  Identification Proof Details in DP Minor Nominee Guardian Details",
        "guardianPin": "Please enter Third Minor Nominee Guardian  PinCode in DP Minor Nominee Guardian Details",
        "guardianRelationshipofGuardian": "Please select  Third Minor Nominee Guardian Relationship With Applicant in DP Minor Nominee Guardian Details",
        "guardianState": "Please enter Third Minor Nominee Guardian  State in DP Minor Nominee Guardian Details",
        "guardianStreet": "Please enter Third Minor Nominee Guardian  Address 3 in DP Minor Nominee Guardian Details",
        "guardianTitle": "Please select Third Minor Nominee Guardian  Title for DP Minor Nominee Guardian Details",
        "nomineeCity": "Please enter Third Nominee City in DP Nominee Details",
        "nomineeCountry": "Please enter Third Nominee Country in DP Nominee Details",
        "nomineeDOB": "Please enter Third Nominee DOB in DP Nominee Details",
        "nomineeEqualShareForNominess": "Please select option for Third Nominee Equal Share For Nominees in DP Nominee Details",
        "nomineeFirstName": "Please enter Third Nominee First Name in DP Nominee Details ",
        "nomineeHouseName": "Please enter Third Nominee Address 1 in DP Nominee Details",
        "nomineeHouseNumber": "Please enter Third Nominee Address 2 in DP Nominee Details",
        "nomineeIdNumber": "Please enter Third Nominee Identification Proof Details in DP Nominee Details",
        "nomineeNomineeIdentificaitonDetails": "Please enter Third Nominee Identification Proof in DP Nominee Details",
        "nomineePin": "Please enter Third Nominee PinCode in DP Nominee Details",
        "nomineeRelationshipwithapplicant": "Please select Third Nominee Relationship With Applicant in DP Nominee Details",
        "nomineeState": "Please enter Third Nominee State in DP Nominee Details",
        "nomineeStreet": "Please enter Third Nominee Address 3 in DP Nominee Details",
        "nomineeTitle": "Please select Third Nominee Title for DP Nominee",
        "sharePercentage": "Please enter Third Nominee the % of Share in DP Nominee Details"
    },
}
