export const tradingValidations = {
    AddDetails: {
        "AlertstoInvestorsbystockExchanges": "Please opt if client wish to receive alerts by Stock Exchanges",
        "electronicContractNote": "Please opt if ECN facility is required",
        "PriorExperience": "Please opt if client has Prior Experience in Investment/Trading",
        "wishtoAvailInternetTrading": "Please opt if client wish to avail Internet Facility",
        emailIdforECN: "Please enter Email ID of ECN"

    },
    AgreementDetails: {
        "FAOexposureagainstholdingagreement": "Please select  status of FAO Exposure Against Holding",
        "kycRecievedType": "Please select  KYC Received Type",
        "POA": "Please select  POA status",
        "WSPdeclaration": "Please select  WPS Declaration",
        "runningAc": "Please select   Running A/c",
        "ECNVarifiedBy": "Please Enter  ECN Verified By ",
        "RunningAccpayoutsettlementtype": "Please select  Running A/c payout settlement type",
        "date": 'Please enter POA signed Date',
        "WSPdate": "Please select  WPS Declaration Date",
        "NROUndertaking": "Please select NRO Undertaking",
        "NREUndertaking": "Please select  NRE Undertaking",
        ECNVarifiedName:'Plese enter ECN Verified by Name',
        ECNVarifiedDate:'Plese enter  ECN verified date'
    },
    GeneralDetails: {
        "kitNO": "Please enter Kit No",
        "ifGeojitEmployee": 'Please select If Geojit Employee'
    },
    NomineeDetails: {
        "GuardianCity": "Please enter City in Guardian details",
        "GuardianCountry": "Please enter Country in Guardian details",
        "GuardianFirstName": "Please enter Guardian First Name",
        "GuardianhouseName": "Please enter Address 1 in Guardian details",
        "GuardianhouseNumber": "Please enter Address 2 in Guardian details",
        "GuardianId": "Please enter Guardian ID in Guardian details",
        "GuardianPIN": "Please enter PinCode in Guardian details",
        "GuardianRelation": "Please select Relationship With Guardian",
        "GuardianState": "Please enter State in Guardian details",
        "Guardianstreet": "Please enter Address 3 in Guardian details",
        "GuardianTitle": "Please select Title for Guardian details",
        "NomineeCity": "Please enter City in Nominee details",
        "NomineeCountry": "Please enter Country in Nominee details",
        "NomineeDOB": "Please enter Nominee DOB in Nominee details",
        "NomineeFirstName": "Please enter Nominee First Name",
        "NomineehouseName": "Please enter Address 1 in Nominee details",
        "NomineehouseNumber": "Please enter Address 2 in Nominee details",
        "NomineeID": "Please enter Nominee ID in Nominee details",
        "NomineePIN": "Please enter PinCode in Nominee details",
        "NomineeState": "Please enter State in Nominee details",
        "Nomineestreet": "Please enter Address 3 in Nominee details",
        "NomineeTitle": "Please select Title for Nominee details",
        "RelationshipWithNominee": "Please select client Relationship With Nominee",
        NomineeIdNumber: 'Please enter Nominee Id number',
        GuardianProofNumber: "Please enter Guardian Proof Number "
    },
    RelationWithGeojit: {
        "Relativeofgeojit": "Please opt if client is Relative Of Geojit Employee",
        'EmployeeCode': "Please enter Employee Code",
        'EmployeeName': "Please enter Employee Name",
    },
    StockBroker: {
        "ClientCode": "Please enter Client Code in Stock Broker details",
        "details": "Please enter Details Of Disputes/ Dues Pending From/ To Such Stock Broker/ Sub Broker/ AP/ Member in Stock Broker Details",
        "Exchange": "Please enter Exchange in Stock Broker Details",
        "MenberClientCode": "Please enter Member Client Code in Stock Broker Details",
        "nameOfMember": "Please enter Name Of Member in Stock Broker Details",
        "stockBroker": "Please enter Stock Broker Name",
        "subBrokerName": "Please enter Name Of Sub Broker in Stock Broker details"
    },
    SubBroker: {
        "BSERegNO": "Please enter BSE SEBI Registration No/ AP Registration No",
        "NSERegNO": "Please enter NSE SEBI Registration No/ AP Registration No",
        "registeredOfficeAddress": "Please enter Registered Office Address in SubBroker Details",
        "subBokerName": "Please enter Sub Broker/ AP Name"
    },
    introducerDetails: {
        statusOfIntroducer: [null],
        IntroducerPhoneNumber: [null],
        nameOfIntroducer: [null],
        IntroducerClientCode: [null],
        IntroducerhouseName: [null],
        IntroducerhouseNumber: [null],
        Introducerstreet: [null],
        IntroducerRemiserCode: 'Please enter Remiser Code in Introducer Details',
        IntroducerRemiserID: 'Please enter Remiser ID in Introducer Details',
        IntroducerApCode: [null],
        leadGeneratorEmpCode: [null],
        leadGeneratorEmpName: [null],
    },
    ThirdPartyPOA: {
        "POAAuthorisedPersonName": "Please enter Authorised Person Name in Third Party POA details",
        "POAdob": "Please enter DOB in Third Party POA details",
        "POAhouseName": "Please enter Address 1 in Third Party POA details",
        "POAhouseNumber": "Please enter Address 2 in Third Party POA details",
        "POAMobile": "Please enter Mobile in Third Party POA details",
        "POAstreet": "Please enter Address 3 in Third Party POA details",
        "proofOfIdentity": "Please enter Proof Of Identity in Third Party POA details",
        POAdocumentNo: "Please enter POA document number in Third Party POA details"
    },
    // clearringMembershipDetails:{
    //     NameofStockExchange:"",
    //     NameofClearingCorporation:"",
    //     ClearingMemberID:"",
    //     SEBIRegistrationNo:"",
    //     TradeName:"",
    //     CMBPID:"",
    //     NameofCoparcenerorMember:"",
    //     Gender:"",
    //     DateofBirth:"",
    //     RelationwithKartha:"",
    //     WhetherCoparcenerorMember:"",
    // },
    // fiss:{
    //     Foreignaddress:"",
    //     Country:"",
    //     State:"",
    //     city:"",
    //     Pin:"",
    //     SEBIRegistrationNo:"",
    //     RBIReferencenumber:"",
    //     RBIapprovaldate:"",
    // }
}